// #pragma once

#undef OMPU_DEF_HELPER_EXTRACTOR_TYPE
#undef OMPU_DEF_HELPER_EXTRACTOR_NAME
#undef OMPU_DEF_HELPER_EXTRACTOR_SPACED
#undef OMPU_DEF_HELPER_EXTRACTOR_SPACED_WITH_SEMICOLON
#undef OMPU_DEF_HELPER_EXTRACTOR_INIT_I
#undef OMPU_DEF_HELPER_EXTRACT_ENUM
#undef OMPU_DEF_HELPER_EXTRACT_PARAMS
#undef OMPU_DEF_HELPER_EXTRACT_VARIABLES
#undef OMPU_DEF_HELPER_EXTRACT_INITIALIZER_LIST

#undef OMPU_DEF_HELPER_EXTRACT_CLASS_TRAITS

#undef OMPU_MIDI_MESSAGE_DEF
#undef OMPU_MIDI_SYSEX_DEF

// #undef OMPU_DEF
