#pragma once

#include "ompu/music/music_fwd.hpp"
#include "ompu/music/ident.hpp"
#include "ompu/music/mod.hpp"
#include "ompu/music/relation.hpp"
#include "ompu/music/degree.hpp"
#include "ompu/music/diatonic.hpp"
#include "ompu/music/interval.hpp"
#include "ompu/music/tone.hpp"
#include "ompu/music/scale.hpp"
#include "ompu/music/key.hpp"
#include "ompu/music/symbol.hpp"
#include "ompu/music/part.hpp"
#include "ompu/music/track.hpp"
#include "ompu/music/chord.hpp"
#include "ompu/music/degreed_chord.hpp"
#include "ompu/music/chord_classifier.hpp"

// #include "ompu/music/resolver.hpp"
// #include "ompu/music/io.hpp"
